prefix:
 "/gpfs/project/daric102/circs_hilbert_scratchgs/repo/circs"
genome_STAR_hg38:
 "/gpfs/project/daric102/circs_hilbert_scratchgs/repo/circs/pipelines/hg38_full"
genome_STAR_hg19:
  "/gpfs/project/daric102/circs_hilbert_scratchgs/repo/circs/pipelines"
lane_ident1:
 "_1"
lane_ident2:
 "_2"
threads:
 12
